language: java
# version numbers
jdk:
    - oraclejdk8

# Use JDK 8u45. The above line just causes the use of a minor version of Java 8.
addons:
  apt:
    packages:
      - oracle-java8-installer

install:
- mvn install
script:
- mvn test -Dmaven.javadoc.skip=true

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
